"""quality end dates for project

Revision ID: 17c30215f583
Revises: 572a77a74b4a
Create Date: 2013-02-11 15:24:02.625326

"""

# revision identifiers, used by Alembic.
revision = '17c30215f583'
down_revision = '572a77a74b4a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('completion_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('assistance_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('test_date', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'test_date')
    op.drop_column('projects', 'assistance_date')
    op.drop_column('projects', 'completion_date')
    ### end Alembic commands ###
