"""userfriendly svn

Revision ID: 39a1c757f558
Revises: 8437c1a360d
Create Date: 2013-06-13 09:00:23.227501

"""

# revision identifiers, used by Alembic.
revision = '39a1c757f558'
down_revision = '8437c1a360d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('svn_login', sa.Unicode(), nullable=True))
    op.execute('UPDATE users SET svn_login=email WHERE svn_login IS NULL;')
    op.alter_column('users', 'svn_login', type_=sa.Unicode, nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'svn_login')
    ### end Alembic commands ###
