"""filler

Revision ID: 483950e462cf
Revises: 538e6ad6eadb
Create Date: 2013-06-12 10:34:17.525855

"""

# revision identifiers, used by Alembic.
revision = '483950e462cf'
down_revision = '538e6ad6eadb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_requests', sa.Column('filler', sa.Boolean(create_constraint=True, name=None), nullable=True))
    op.execute('UPDATE customer_requests SET filler=False WHERE filler IS NULL;')
    op.alter_column('customer_requests', 'filler', type_=sa.Boolean(create_constraint=True, name=None), nullable=False)
    op.execute('UPDATE contracts SET days=0 WHERE days IS NULL;')
    op.alter_column('contracts', 'days', type_=sa.Float(precision=2, asdecimal=False), nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_requests', 'filler')
    ### end Alembic commands ###
