"""searchable applications

Revision ID: 570b3a41fca9
Revises: 8437c1a360d
Create Date: 2013-04-18 15:08:33.690375

"""

# revision identifiers, used by Alembic.
revision = '570b3a41fca9'
down_revision = '8437c1a360d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('searchable', sa.Boolean(create_constraint=True, name=None), nullable=True))
    op.execute('UPDATE applications SET searchable=True WHERE searchable IS NULL;')
    op.alter_column('applications', 'searchable', type_=sa.Boolean(create_constraint=True, name=None), nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'searchable')
    ### end Alembic commands ###
