"""add karma_id to project

Revision ID: 572a77a74b4a
Revises: None
Create Date: 2013-01-09 21:42:33.705837

"""

# revision identifiers, used by Alembic.
revision = '572a77a74b4a'
down_revision = '3e02114064fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('karma_id', sa.String(length=None, convert_unicode=False, assert_unicode=None, unicode_error=None, _warn_on_bytestring=False), nullable=True))
    op.drop_column('groups', u'name')
    op.drop_column('users', u'login')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(u'login', sa.VARCHAR(length=None, convert_unicode=False, assert_unicode=None, unicode_error=None, _warn_on_bytestring=False), nullable=True))
    op.drop_column('projects', 'karma_id')
    op.add_column('groups', sa.Column(u'name', sa.VARCHAR(length=None, convert_unicode=False, assert_unicode=None, unicode_error=None, _warn_on_bytestring=False), nullable=True))
    ### end Alembic commands ###
