"""add inception date

Revision ID: 8437c1a360d
Revises: 17c30215f583
Create Date: 2013-02-11 17:44:55.901812

"""

# revision identifiers, used by Alembic.
revision = '8437c1a360d'
down_revision = '17c30215f583'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('inception_date', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'inception_date')
    ### end Alembic commands ###
